# Site text
title: "Resilience by Cyan"
description: "Notes on research & projects"

# Menu items for header navigation
menu:
  - { name: "Home", link: "/" }
  - { name: "About", link: "/about/" }
  - { name: "Projects", link: "/projects/" }

# Social icons
social:
  - { icon: "github", link: "https://github.com/KUcyans" }
  - { icon: "linkedin", link: "https://www.linkedin.com/in/cyan-yong-ho-jo-a991702b0/" }
